//
// Created by d-qql on 17.10.2021.
//

#ifndef COMPUTATIONALMATHSOLVER_UNDERFINEDCOEFFICIENTSMETHOD_HPP
#define COMPUTATIONALMATHSOLVER_UNDERFINEDCOEFFICIENTSMETHOD_HPP


class UnderfinedCoefficientsMethod {

};


#endif //COMPUTATIONALMATHSOLVER_UNDERFINEDCOEFFICIENTSMETHOD_HPP
